name: quantumoonlight
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anyjson=0.3.3
  - argon2-cffi=21.1.0
  - arrow=1.2.2
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.10.3
  - bcrypt=3.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - click=8.0.4
  - colour=0.1.5
  - cvxpy=1.2.1
  - cvxpy-base=1.2.1
  - cycler=0.11.0
  - dataclasses=0.8
  - deap=1.0.2
  - ecos=2.0.10
  - et_xmlfile=1.1.0
  - flask=1.1.2
  - flask-login=0.5.0
  - flask-sqlalchemy=2.5.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - furl=2.1.3
  - giflib=5.2.1
  - greenlet=1.1.0
  - h11=0.13.0
  - hdf5=1.12.1
  - idna=3.3
  - imbalanced-learn=0.7.0
  - infinity=1.5
  - iniconfig=1.1.1
  - intervals=0.9.2
  - itsdangerous=2.0.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - libblas=3.9.0
  - libcurl=7.82.0
  - libcxx=14.0.6
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.4.2
  - libgfortran
  - libgfortran5
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libzlib=1.2.12
  - llvm-openmp
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - munkres=1.1.4
  - mysql-connector-c=6.1.11
  - mysqlclient=2.0.3
  - ncurses=6.3
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openpyxl=3.0.9
  - openssl=1.1.1q
  - orderedmultidict=1.0.1
  - osqp=0.6.2.post0
  - outcome=1.2.0
  - packaging=21.3
  - pandas=1.4.2
  - passlib=1.7.4
  - pendulum=2.1.2
  - phonenumbers=8.12.51
  - pillow=9.2.0
  - pip=22.1.2
  - pluggy=1.0.0
  - py=1.11.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - pytest=7.1.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.1
  - pytzdata=2020.1
  - pyzmq=23.2.0
  - qdldl-python=0.1.5
  - readline=8.1.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - scoop=0.7.1.1
  - scs=3.2.0
  - selenium=4.3.0
  - setuptools=61.2.0
  - six=1.16.0
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - sqlalchemy=1.4.32
  - sqlalchemy-utils=0.38.2
  - sqlite=3.38.5
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.1
  - trio=0.19.0
  - trio-websocket=0.9.2
  - typing_extensions=4.3.0
  - tzdata=2022a
  - urllib3=1.26.10
  - werkzeug=2.0.3
  - wheel=0.37.1
  - wsproto=0.14.0
  - wtforms=2.3.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - cryptography==37.0.4
    - dill==0.3.5.1
    - dlx==1.0.4
    - docplex==2.23.222
    - fastdtw==0.3.4
    - flask-ckeditor==0.4.6
    - h5py==3.2.1
    - inflection==0.5.1
    - lxml==4.9.1
    - more-itertools==8.13.0
    - mpmath==1.2.1
    - multitasking==0.0.11
    - ntlm-auth==1.5.0
    - pbr==5.9.0
    - ply==3.11
    - psutil==5.9.1
    - python-constraint==1.4.0
    - qiskit==0.36.2
    - qiskit-aer==0.10.4
    - qiskit-aqua==0.9.5
    - qiskit-ibmq-provider==0.19.1
    - qiskit-ignis==0.7.1
    - qiskit-machine-learning==0.4.0
    - qiskit-terra==0.20.2
    - quandl==3.7.0
    - requests==2.28.1
    - requests-ntlm==1.1.0
    - retworkx==0.11.0
    - stevedore==4.0.0
    - symengine==0.9.2
    - sympy==1.10.1
    - tweedledum==1.1.1
    - websocket-client==1.3.3
    - websockets==10.3
    - yfinance==0.1.74
