pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Stage
  lockBehavior: sequential
  jobs:
  - deployment: Job
    environment: Lock_environment
    strategy:
      runOnce:
        deploy:
          steps:
          
          - task: AzureWebAppContainer@1
            displayName: 'Deploy dell''immagine Docker sull''Azure Web App'
            inputs:
              appName: 'quantumoonlight'
              containers: 'skipper98/quantumoonlight:latest'
              azureSubscription: 'Azure for Students(0e898bbd-4a52-42c0-af70-42233e2b4caa)'
              resourceGroupName: 'quantumoonlight-resource'