trigger:
- master 

pool: 'Default'

stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: 'latest'
        containerRegistry: 'Docker Hub Connection'
        repository: 'skipper98/quantumoonlight'
- stage: Test
  dependsOn: Build
  displayName: 'Run Test'
  jobs:
    - job: TestDockerImage
      displayName: 'Test Docker image'
      steps:
      - task: Bash@3
        displayName: 'Run Docker image'
        inputs:
          targetType: 'inline'
          script: |
            docker run --rm -d -p 5000:5000 --env ENVIRONMENT=Test --name quantum_container skipper98/quantumoonlight
            sleep 10s
      - script: |
          docker exec $(docker ps --filter ancestor=skipper98/quantumoonlight -q) pytest -p no:warnings --junitxml=TEST-result.xml
        displayName: 'Run tests'
        continueOnError: false
      - script: |
          container_id=$(docker ps --filter ancestor=skipper98/quantumoonlight -q)
          docker stop $container_id
        displayName: 'Stop Docker container'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-result.xml'
          failTaskOnFailedTests: true
- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Test
  jobs:
  - job: Deploy
    steps:
    - task: Docker@2
      displayName: 'Push Docker Image to registry'
      inputs:
        command: 'push'
        containerRegistry: 'Docker Hub Connection'
        repository: 'skipper98/quantumoonlight'
        tags: 'latest'
#    - script: |
#        docker rmi skipper98/quantumoonlight:latest
#      displayName: 'Delete local Docker Image'
    - task: AzureWebAppContainer@1
      displayName: 'Deploy dell''immagine Docker sull''Azure Web App'
      inputs:
        appName: 'quantumoonlight'
        containers: 'skipper98/quantumoonlight:latest'
        azureSubscription: 'Azure for Students(0e898bbd-4a52-42c0-af70-42233e2b4caa)'
        resourceGroupName: 'quantumoonlight-resource'
