trigger:
- master 

pool: 'Default'

stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
        containerRegistry: 'Docker Hub Connection'
        repository: 'skipper98/quantumoonlight'

- stage: Test
  displayName: 'Run Tests'
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - task: Bash@3
      displayName: 'Install packages'
      inputs:
        targetType: 'inline'
        script: |
          pip install pytest 
          pytest
      continueOnError: false
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'


- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Test
  jobs:
  - job: Deploy
    steps:
    - task: Docker@2
      displayName: 'Push Docker Image to registry'
      inputs:
        command: 'push'
        containerRegistry: 'Docker Hub Connection'
        repository: 'skipper98/quantumoonlight'
        tags: 'latest'
    - task: AzureWebAppContainer@1
      displayName: 'Deploy dell''immagine Docker sull''Azure Web App'
      inputs:
        appName: 'quantumoonlight'
        containers: 'skipper98/quantumoonlight:latest'
        azureSubscription: 'Azure for Students(0e898bbd-4a52-42c0-af70-42233e2b4caa)'
        resourceGroupName: 'quantumoonlight-resource'
