pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Stage
  lockBehavior: sequential
  jobs:
  - deployment: Job
    environment: Lock_environment
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
              