pool:
  vmImage: 'ubuntu-latest'
  lockBehavior: sequential

stages:
- stage: Stage
  jobs:
  - deployment: Job
    environment: Lock_environment
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Docker@2
            displayName: 'Build e push dell''immagine Docker'
            inputs:
              containerRegistry: 'Docker Hub Connection'
              repository: 'skipper98/quantumoonlight'
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
              buildContext: 'app/'
              tags: 'latest'
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Azure for Students(0e898bbd-4a52-42c0-af70-42233e2b4caa)'
              appName: 'quantumoonlight'
              deployToSlotOrASE: true
              resourceGroupName: 'QuantuMoonLight-resource'
              slotName: 'production'
              containers: 'skipper98/quantumoonlight:latest'
