# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master #elenco di rami per cui il push attiva un esecuzione

pool:
  vmImage: ubuntu-latest #pool in cui vengono eseguiti i processi della pipeline

steps:
  - task: UsePythonVersion@0 #specifica la versione di python utilizzata. Con strategy vai a definire più versioni di python
    inputs: # non verse per il deploy
      versionSpec: '3.9'

jobs:
- deployment: "Deploy Web App"
  displayName: "My Deploy"
  pool:
    vImage: ubuntu-latest
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo "pipeline start..."
        - script: cd git-projects/QaaS-QuantuMoonLight
        - script: conda activate quantumoonlight
        - script: flask run --host=0.0.0.0
