trigger:
- master

resources:
- repo: self

variables:
  imageName: 'skipper98/quantumoonlight'
  tag: 'latest'
  # DOCKER_BUILDKIT: 1

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build and push image'
    jobs:
      - job: Build
        displayName: 'Build and push image'
        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: 'buildAndPush'
            dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            tags: |
              $(tag)

