# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - task: AzureCLI@2
            inputs: 
             azureSubscription: $(azureSubscription)
             scriptType: bash
             scriptLocation: inlineScript
             inlineScript: |
               az vm run-command invoke --command-id RunShellScript --resource-group QuantuMoonLight-VM_group --name QuantuMoonLight-VM --scripts "cd ~/git-projects/QaaS-QuantuMoonLight;source activate quantumoonlight;nohup flask run -h 0.0.0.0 -p 5000 &"